### ISSUE TITLE
Using busboy as a middleWare

### ISSUE THREAD

**Issue by aonurozcan** [thaume/s3-streaming#1]
Hi. I am new to NodeJs. How can I use busboy as a middleware. I need s3 url of file **after** it was uploaded. Because I will do some database operations with the url.

``` javascript
var s3UploadService = require('../util/Aws-Streaming');
app.post("/testUpload", function (req, res) {
  return s3UploadService(req, function (err, url) {
    // Do some database operations.
  });
});
```

``` javascript
var s3UploadService = require('../util/Aws-Streaming');
app.post("/testUpload", s3UploadService, function (req, res) {
  // I can not pass req parameter to s3UploadService this way.
});
```

Either way I couldn't use busboy as middleware. If you can help, I will be appreciated. Thank you.

**Comment by thaume** [comment]
Don't use it as a middleware, just use it in your route like here : https://github.com/thaume/s3-streaming/blob/master/routes/index.js#L7

Then you can get the URL back from the callback.

**Comment by aonurozcan** [comment]
Thank you so much.
