### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by machbio** [thaume/s3-streaming#2]
Tom, could you provide license information for this repository. Thanks.

**Comment by thaume** [comment]
Hey @machbio here it is : https://github.com/thaume/s3-streaming/commit/ff175913a08666b85b46a67745f83a329e963343

I don't know what you intend on doing with this repo but the code is pretty old, careful using it ;)

**Comment by machbio** [comment]
Thank you - for the Blog post and Repo
